### ISSUE TITLE
npm run build errored

### ISSUE THREAD

**Issue by max-mapper** [jondashkyle/enoki-starterkit#1]
```
~/src/js/enoki-starterkit 🐈  git diff
diff --git a/content/projects/04-transatlantic-editions/project.txt b/content/projects/04-transatlantic-editions/project.txt
index 863e3e7..544fe58 100644
--- a/content/projects/04-transatlantic-editions/project.txt
+++ b/content/projects/04-transatlantic-editions/project.txt
@@ -1,10 +1,17 @@
 title: Masterpieces of Photography
+
 ----
+
 tags:
   - book
   - 1952
   - photography
   - ernst heiniger
   - composition
+
+
 ----
-text: New York City: Transatlantic Editions, 1952.
\ No newline at end of file
+
+text: New York City: Transatlantic Editions, 1952.
+
+hello
\ No newline at end of file
~/src/js/enoki-starterkit 🐈  node -v
v6.11.0

~/src/js/enoki-starterkit 🐈  npm run build

> enoki-starterkit@1.0.2 build /Users/max/src/js/enoki-starterkit
> enoki build -o public/ && browserify site/ -o public/bundle.js -t require-globify -t enoki/transform -t yo-yoify -t es2040

/Users/max/src/js/enoki-starterkit/node_modules/yargs/yargs.js:1079
      else throw err
           ^

TypeError: Object.values is not a function
    at copyFiles (/Users/max/src/js/enoki-starterkit/node_modules/enoki/bin/build.js:48:14)
    at route (/Users/max/src/js/enoki-starterkit/node_modules/enoki/bin/build.js:29:41)
    at Object.build [as handler] (/Users/max/src/js/enoki-starterkit/node_modules/enoki/bin/build.js:20:3)
    at Object.self.runCommand (/Users/max/src/js/enoki-starterkit/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/Users/max/src/js/enoki-starterkit/node_modules/yargs/yargs.js:990:30)
    at Object.get [as argv] (/Users/max/src/js/enoki-starterkit/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/Users/max/src/js/enoki-starterkit/node_modules/enoki/bin/index.js:39:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

```

**Comment by jondashkyle** [comment]
Thanks @max, patched that one up real quick! Writing tests is a big item on the immediate list :)
